package com.ldal.pigeonapp;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Cursor;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import java.util.ResourceBundle;

public class ProfileScene implements Initializable
{
    @FXML
    private Label mailDeclarer;
    @FXML
    private Label usernameDeclarer;
    @FXML
    private Label IdDeclarer;
    @FXML
    private AnchorPane anchorPane;
    @FXML
    private Label dateCreatedDeclarer;
    @FXML
    private Label lastLogedinDeclarer;
    SQLServer sqlServer = new SQLServer();
    String[] SplashScreensTexts;
    @FXML
    private Label SplashScreenTexter;
    @FXML
    public void Backtomenu(ActionEvent event)
    {
        try
        {
            Parent root = FXMLLoader.load(PigeonApplication.class.getResource("/EmailSelector.fxml"));
            Scene scene = new Scene(root);
            Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            stage.setScene(scene);
        } catch (IOException e) {throw new RuntimeException(e);}
    }

    @FXML
    public void profileDeleterStart(ActionEvent event)
    {
        try
        {
            Parent root = FXMLLoader.load(PigeonApplication.class.getResource("/ProfileDeletionScene.fxml"));
            Scene scene = new Scene(root);
            Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
            stage.setScene(scene);
        } catch (IOException e) {throw new RuntimeException(e);}
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle)
    {
        Circle profileCircle = new Circle(75, Color.CRIMSON);

        Label initialText = new Label(String.valueOf(Client.getUser().getLogin().charAt(0)) + String.valueOf(Client.getUser().getLogin().charAt(1)));
        initialText.setTextFill(Color.WHITE);
        initialText.setStyle("-fx-font-size: 40px; -fx-font-weight: bold;");

        StackPane circleWithText = new StackPane(profileCircle, initialText);
        circleWithText.setPrefSize(120, 120);

        circleWithText.setLayoutX(310);
        circleWithText.setLayoutY(222);

        anchorPane.getChildren().add(circleWithText);

        mailDeclarer.setText("Email: " + Client.getUser().getEmail());
        usernameDeclarer.setText("Username: " + Client.getUser().getLogin());
        IdDeclarer.setText("Account ID: " + Client.getUser().getId());
        String dateCreated = sqlServer.getDateCreatedFromID(Client.getUser().getLogin());
        dateCreatedDeclarer.setText("Date Created: " + dateCreated);
        lastLogedinDeclarer.setText("Logged In Since: " + LocalDateTimer.localDateTime());

        SplashScreensTexts = new String[]
                {
                        "Don't forget to check out Cruellete!",
                        "Don't forget to check out Shiftendo!",
                        "Don't forget to check out\nFusion Blast!",
                        "Don't forget to check out\n@CaptainCaramel (On YT)!",
                        "There’s no deeper lore. Or is there?",
                        "Don't you dare go hollow!",
                        "We were gonna add a battle pass\nhere but nah.",
                        "This tip was generated by\na sleep-deprived developer.",
                        "To: The boy who resembles carlo.",
                        "Link the flame. Read the mail.",
                        "This message requires 40 INT to understand.",
                        "*Not enough insight to comprehend this splash tip*",
                        "Zero pigeons were harmed in the\n\t making of this app.",
                        "From: Hanako\nSubject: NocturneOp55N1\n\tMeet me at the embers.",
                        "From: Monte | To: Noct\nThe game was rigged from\n the beginning.",
                        "\tI see.\n\tSo this thing...\n\tin the palm of my hand...\n\tis a heart",
                        "R2-D2 tried to decode our code...\nhe gave up.",
                        "CC you fuse,\nGugena you blast\n and Tolchok...you just be tolchok",
                        "I heard there was a knight\nthat went hollow",
                        "We made it to to the major leagues\n\tchoom!"
                };

        Random random = new Random();
        WarnerClass.WarnerError(SplashScreenTexter, SplashScreensTexts[random.nextInt(SplashScreensTexts.length)], true);
        SplashScreenTexter.setStyle("-fx-text-fill: darkgray; -fx-font-size: 18; -fx-opacity: 0.82;");
    }
}
